### ISSUE TITLE
Please show us what the app does

### ISSUE THREAD

**Issue by TylerL-uxai** [ryanflorence/react-project#18]
I'd like a simple screen shot of this app so I know how it works without having to read an entire 10 paragraph document. Examples communicate better than paragraphs. This is Jakob Nielsen's expertise I'm paraphrasing.

Thank you.

**Comment by ryanflorence** [comment]
You're right, but I am purposefully selecting for people who are willing to dig in right now. Were I to have a lot of great marketing there'd be more usage, it would look more appealing and production ready. That  means people opening issues and asking questions instead of people digging in and fixing things :)
